dist: trusty

language: java
node_js:
  - 10

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - client/node_modules/

addons:
  sonarcloud:
    organization: ${SONAR_ORGANIZATION}
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - nvm install 10

before_script:
  - npm install --prefix client/

script:
  - npm run build --prefix client/
  - mvn clean test jacoco:report coveralls:report
