dist: trusty

language: java
node_js:
  - 10

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - client/node_modules/

addons:
  sonarcloud:
    organization: "myawesomefinalprojectgroup"
    token:
      secure: ${SONAR_TOKEN}

before_install:
  - nvm install 10

before_script:
  - npm install --prefix client/

script:
  - npm run build --prefix client/
  - npm run lint
  - mvn clean test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - sonar-scanner