spring:
  profiles:
    active: local

---

spring:
  profiles: qa
  datasource:
    url: jdbc://mysql://localhost:3306/qa
    password: 12345
  resources:
    static-locations=classpath:/storage/,classpath:/src/main/resources/public

server:
  port: 9001

---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto=update

  datasource:
    url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username=springuser
    password=ThePassword

server:
  port: 9002