spring:
  profiles:
    active: dev

---


spring:
  profiles: dev
  resources:
    static-locations=classpath:/storage/**,classpath:/src/main/resources/public

---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

---
spring:
  profiles: prod

  datasource:
    url=jdbc:postgresql://procmain.eu:5432/fsbook
    username=postgres
    password=FS9final