spring:
  profiles:
    active: local

---
spring:
  profiles: local
  resources:
    static-locations=classpath:/storage/,classpath:/src/main/resources/public

---
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

---
spring:
  profiles: prod
  datasource:
    url: jdbc://mysql://localhost:3306/qa
    password: 12345
